mods.avaritia.compressor.removeByOutput(item("avaritia:singularity",0))
mods.avaritia.compressor.recipeBuilder()
    .input(item("minecraft:iron_block"))
    .output(item("avaritia:singularity",0))
    .inputCount(2147483647)
    .register()