mods.compactmachines3.miniaturization.removeByOutput(item("compactmachines3:wallbreakable"))
mods.compactmachines3.miniaturization.recipeBuilder()
    .name('mekeawall')
    .input(item('minecraft:redstone'))
    .output(item('compactmachines3:wallbreakable')*6)
    .symmetrical()
    .ticks(10)
    .shape([['i',],['r']])
    .key('r', blockstate('minecraft:redstone_wire'))
    .key('i', blockstate('mekanism:basicblock',8))
    .register()

//でばいすの難化
crafting.removeByOutput(item("compactmachines3:psd"))
crafting.shapedBuilder()
    .name('valine_expart_1_12_2:psd')
    .output(item("compactmachines3:psd"))
    .matrix(" G ","ETE"," I ")
    .key('E',item("minecraft:ender_pearl"))
    .key('G',item("minecraft:glass_pane"))
    .key('T',item('mekanism:energytablet').withNbt(['mekData': ['energyStored': 1000000.0D]]))
    .key('I',item("minecraft:iron_ingot"))
    .register()